# Node types
NODE_CLAIM = "Claim"
NODE_OBLIGATION = "Obligation"
NODE_RIGHT = "Right"
NODE_CONDITION = "Condition"
NODE_ACTION = "Action"
NODE_DEADLINE = "Deadline"
NODE_GAP = "Gap"

# Relationship types
REL_CONDITIONED_ON = "CONDITIONED_ON"
REL_HAS_DEADLINE = "HAS_DEADLINE"
REL_APPLIES_TO_ROLE = "APPLIES_TO_ROLE"
REL_DERIVED_FROM_SPAN = "DERIVED_FROM_SPAN"
REL_CONFLICTS_WITH = "CONFLICTS_WITH"
